### PR TITLE
Fix: Reload homepage after changing 'preferred media' setting

### LINKED ISSUE #212: BUG in "preferred media"
After selecting a preferred media for example - movies and shows , it didnt had any affect on the content which is shown on the homepage . It just removed anime providers from the selection in the homepage , random option works tho according to "preferred media" but after relaunching it just shows any of the provider including anime randomly .

### PR DESCRIPTION
**Pull request by Jacekun**
Closes #212 

Note: Saving the api name on HOMEPAGE_API key solves the issue of persistent homepage after changing setting. It also makes sense since randomly choosing a provider makes it the last provider used. Also, moved the filtering code to AppUtils class.

### CODE REVIEW

**Comment by LagradOst** [comment]
No, this wont be accepted due to saving instance as a variable.

**Comment by Jacekun** [comment]
> No, this wont be accepted due to saving instance as a variable.

I see. I'll change it to something else then. Maybe on applying setting, randomizing it there and saving the key.

**Comment by LagradOst** [comment]
Yes, I dont want dependencies if it can be avoided and I think saving it will result in memory issues and android context fuckery.

File: app/src/main/java/com/lagradost/cloudstream3/ui/settings/SettingsFragment.kt [hunk 1]
```diff
@@ -165,28 +169,28 @@ class SettingsFragment : PreferenceFragmentCompat() {
...
+                prefNames.toList(),
+                prefValues.indexOf(currentPrefMedia),
+                getString(R.string.preferred_media_settings),
+                true,
+                {}) {
+                settingsManager.edit()
+                    .putInt(getString(R.string.preferred_media_settings), prefValues[it])
+                    .apply()
+                var apiRandom = AppUtils.filterProviderByPreferredMedia(apis, prefValues[it]).random()
+                AcraApplication.context?.setKey(HOMEPAGE_API, apiRandom.name)
```
Comment (LagradOst) [inline app/src/main/java/com/lagradost/cloudstream3/ui/settings/SettingsFragment.kt:190]: Why AcraApplication and not just context?.

Comment (Jacekun) [reply app/src/main/java/com/lagradost/cloudstream3/ui/settings/SettingsFragment.kt:190]: Ah. Forgot to auto import the necessary class namespace.

Comment (Jacekun) [reply app/src/main/java/com/lagradost/cloudstream3/ui/settings/SettingsFragment.kt]: Done changes

**Comment by Jacekun** [comment]
On an unrelated note: Should Search filter be affected by this setting? So that when Movies/TV or Anime is selected, only those options can be selected, along with 'Torrent'.

**Comment by LagradOst** [comment]
No, search should not be affected because there already exist a search filter.

**Comment by Jacekun** [comment]
> No, search should not be affected because there already exist a search filter.

No, I don't mean the search results. I meant the search filter choices. So for instance, I enabled Movie and TV only. The option for anime shouldn't be visible

**Comment by LagradOst** [comment]
No

**Comment by LagradOst** [comment]
LGTM, ready to merge?
