### PR TITLE
Dramasee and WatchAsian fix to support asianload domain. Fixes #526

### LINKED ISSUE #526: No links found
I tried aatching the witch part 1 on dramasee and watchasian, but it alaways says no links found. When i tried watching on their website it works

### PR DESCRIPTION
**Pull request by Jacekun**

### CODE REVIEW

File: app/src/main/java/com/lagradost/cloudstream3/extractors/helper/AsianEmbedHelper.kt [hunk 1]
```diff
@@ -8,18 +8,16 @@ import com.lagradost.cloudstream3.utils.loadExtractor
...
-                        //Log.i("AsianEmbed", "Result => (datavid) ${datavid}")
-                        if (datavid.isNotEmpty()) {
-                            val res = loadExtractor(datavid, url, callback)
-                            Log.i("AsianEmbed", "Result => ($res) (datavid) ${datavid}")
-                        }
+            // Fetch links
+            val doc = app.get(url).document
+            val links = doc.select("div#list-server-more > ul > li.linkserver")
+            if (!links.isNullOrEmpty()) {
+                links.forEach {
```
Comment (LagradOst) [inline app/src/main/java/com/lagradost/cloudstream3/extractors/helper/AsianEmbedHelper.kt:15]: you can use apmap for parallel loading

File: app/src/main/java/com/lagradost/cloudstream3/movieproviders/WatchAsianProvider.kt [hunk 2]
```diff
@@ -178,11 +178,23 @@ class WatchAsianProvider : MainAPI() {
...
+                url.startsWith("https://asianembed.io") -> {
+                    AsianEmbedHelper.getUrls(url, callback)
+                }
+                url.startsWith("https://asianload.io") -> {
+                    AsianEmbedHelper.getUrls(url, callback)
+                }
+                url.startsWith("https://embedsito.com") -> {
+                    val extractor = XStreamCdn()
+                    extractor.domainUrl = "embedsito.com"
+                    extractor.getUrl(url).forEach { link ->
```
Comment (LagradOst) [inline app/src/main/java/com/lagradost/cloudstream3/movieproviders/WatchAsianProvider.kt:191]: it is preferred to use getSafeUrl in this case as it makes sure that the code does not throw errors, getUrl can throw errors. https://github.com/LagradOst/CloudStream-3/blob/3fe361586e3248ffecd44b458da06bfe81855229/app/src/main/java/com/lagradost/cloudstream3/utils/ExtractorApi.kt#L186

File: app/src/main/java/com/lagradost/cloudstream3/movieproviders/DramaSeeProvider.kt [hunk 3]
```diff
@@ -160,12 +160,15 @@ class DramaSeeProvider : MainAPI() {
...
             if (item.isNotEmpty()) {
                 count++
-                var url = fixUrl(item.trim())
+                val url = fixUrl(item.trim())
                 //Log.i(this.name, "Result => (url) ${url}")
                 when {
                     url.startsWith("https://asianembed.io") -> {
                         AsianEmbedHelper.getUrls(url, callback)
                     }
+                    url.startsWith("https://asianload.io") -> {
```
Comment (LagradOst) [inline app/src/main/java/com/lagradost/cloudstream3/movieproviders/DramaSeeProvider.kt:169]: here you actually can use || if two statements run the same code

**Review by LagradOst — APPROVED** [review]
LGTM, minor code changes for better quality

**Comment by Jacekun** [comment]
Will make these changes later

**Comment by Jacekun** [comment]
Ready for merge

File: app/src/main/java/com/lagradost/cloudstream3/movieproviders/DramaSeeProvider.kt [hunk 4]
```diff
@@ -160,16 +160,16 @@ class DramaSeeProvider : MainAPI() {
...
                 when {
-                    url.startsWith("https://asianembed.io") -> {
+                    url.startsWith("https://asianembed.io") || url.startsWith("https://asianload.io") -> {
                         AsianEmbedHelper.getUrls(url, callback)
                     }
                     url.startsWith("https://embedsito.com") -> {
                         val extractor = XStreamCdn()
                         extractor.domainUrl = "embedsito.com"
-                        extractor.getUrl(url).forEach { link ->
+                        extractor.getSafeUrl(url)?.apmap { link ->
```
Comment (LagradOst) [inline app/src/main/java/com/lagradost/cloudstream3/movieproviders/DramaSeeProvider.kt:172]: forEach(callback) should be used here because the code do not do any get requests and therefore does not have to be parallel
